# server
server:
  port: 8080

# jdbc
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/et
    username: root
    password: 12345678
  mongodb:
    uri: mongodb://localhost:27017/EmotionTalk

  main:
    allow-bean-definition-overriding: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # jpa
  jpa:
    hibernate:
      ddl-auto: update

    # jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # log
  output:
    ansi:
      enabled: always

  profiles:
    include: oauth

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/rickyhong/upload/

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
